use_frameworks!

platform :ios, '8.0'

target 'JYPodsUtils_Example' do
  pod 'JYPodsUtils', :podspec => '../JYPodsUtils.podspec'

  target 'JYPodsUtils_Tests' do
    inherit! :search_paths

    
  end
end
